/**
 * Vditor 工具栏表情面板：在默认少量 emoji 基础上扩展常用 GitHub 风格 shortcode。
 * 值须为 Unicode 字符（非含 `.` 的 URL），以便走 vditor 文本表情分支。
 */

const VDITOR_EMOJI_BASE: Record<string, string> = {
  '+1': '👍',
  '-1': '👎',
  confused: '😕',
  eyes: '👀',
  heart: '❤️',
  rocket: '🚀',
  smile: '😄',
  tada: '🎉',
};

/** 扩展：日常协作、情绪与常见符号 */
const VDITOR_EMOJI_EXTENDED: Record<string, string> = {
  '100': '💯',
  accepted: '🉑',
  anger: '💢',
  angry: '😠',
  astonished: '😲',
  bell: '🔔',
  blush: '😊',
  boom: '💥',
  bow: '🙇',
  bread: '🍞',
  bulb: '💡',
  biceps: '💪',
  clap: '👏',
  coffee: '☕',
  cold_sweat: '😰',
  computer: '💻',
  construction: '🚧',
  cry: '😢',
  dart: '🎯',
  dizzy: '😵',
  drooling: '🤤',
  ear: '👂',
  'eight_spoked_asterisk': '✳️',
  exclamation: '❗',
  eyes_rolling: '🙄',
  facepalm: '🤦',
  file_folder: '📁',
  fire: '🔥',
  fist: '✊',
  flags: '🏁',
  folded_hands: '🙏',
  gear: '⚙️',
  ghost: '👻',
  gift: '🎁',
  grin: '😁',
  hammer: '🔨',
  handshake: '🤝',
  headset: '🎧',
  heavy_check_mark: '✔️',
  hourglass: '⌛',
  hugging: '🤗',
  hundred: '💯',
  icecream: '🍦',
  innocent: '😇',
  joy: '😂',
  key: '🔑',
  laughing: '😆',
  leftwards_arrow: '←',
  link: '🔗',
  lock: '🔒',
  memo: '📝',
  metal: '🤘',
  moneybag: '💰',
  monocle: '🧐',
  moon: '🌙',
  muscle: '💪',
  nail_care: '💅',
  neutral_face: '😐',
  'no_entry': '⛔',
  notebook: '📓',
  nurse: '🧑‍⚕️',
  ok_hand: '👌',
  open_book: '📖',
  package: '📦',
  pencil2: '✏️',
  phone: '📱',
  pig: '🐷',
  pill: '💊',
  point_down: '👇',
  point_left: '👈',
  point_right: '👉',
  point_up: '👆',
  poop: '💩',
  pray: '🙏',
  pushing_hand: '🫸',
  question: '❓',
  rainbow: '🌈',
  raised_hands: '🙌',
  recycle: '♻️',
  relieved: '😌',
  robot: '🤖',
  rotating_light: '🚨',
  satisfied: '😆',
  scream: '😱',
  see_no_evil: '🙈',
  shamrock: '☘️',
  sheep: '🐑',
  shell: '🐚',
  shushing: '🤫',
  sleepy: '😪',
  slight_frown: '🙁',
  slight_smile: '🙂',
  sleepy_bed: '🛌',
  sparkles: '✨',
  speak_no_evil: '🙊',
  speech_balloon: '💬',
  star: '⭐',
  star2: '🌟',
  sunglasses: '😎',
  sweat_smile: '😅',
  thinking_face: '🤔',
  thumbsdown: '👎',
  thumbsup: '👍',
  tired_face: '😫',
  triangular_flag: '🚩',
  triumph: '😤',
  two_hearts: '💕',
  umbrella: '☂️',
  unicorn: '🦄',
  unlock: '🔓',
  up: '⬆️',
  volcano: '🌋',
  wave: '👋',
  weary: '😩',
  whistle: '🤫',
  wink: '😉',
  wolf: '🐺',
  woman_technologist: '👩‍💻',
  wrench: '🔧',
  writing_hand: '✍️',
  x: '❌',
  yarn: '🧶',
  yellow_heart: '💛',
  yin_yang: '☯️',
  zap: '⚡',
  zebra: '🦓',
  zipper_mouth: '🤐',
};

export function getVditorEmojiMap(): Record<string, string> {
  return { ...VDITOR_EMOJI_BASE, ...VDITOR_EMOJI_EXTENDED };
}
